//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.ServiciosGUC {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserData", Namespace="http://schemas.datacontract.org/2004/07/SecurityService")]
    [System.SerializableAttribute()]
    public partial class UserData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebInventario2._0.ServiciosGUC.Application[] ApplicationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AuthenticatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebInventario2._0.ServiciosGUC.ApplicationCentroCosto[] CentrosCostosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ForeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebInventario2._0.ServiciosGUC.ApplicationMenu[] MenusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebInventario2._0.ServiciosGUC.Application[] Applications {
            get {
                return this.ApplicationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationsField, value) != true)) {
                    this.ApplicationsField = value;
                    this.RaisePropertyChanged("Applications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Authenticated {
            get {
                return this.AuthenticatedField;
            }
            set {
                if ((this.AuthenticatedField.Equals(value) != true)) {
                    this.AuthenticatedField = value;
                    this.RaisePropertyChanged("Authenticated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebInventario2._0.ServiciosGUC.ApplicationCentroCosto[] CentrosCostos {
            get {
                return this.CentrosCostosField;
            }
            set {
                if ((object.ReferenceEquals(this.CentrosCostosField, value) != true)) {
                    this.CentrosCostosField = value;
                    this.RaisePropertyChanged("CentrosCostos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ForeName {
            get {
                return this.ForeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ForeNameField, value) != true)) {
                    this.ForeNameField = value;
                    this.RaisePropertyChanged("ForeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebInventario2._0.ServiciosGUC.ApplicationMenu[] Menus {
            get {
                return this.MenusField;
            }
            set {
                if ((object.ReferenceEquals(this.MenusField, value) != true)) {
                    this.MenusField = value;
                    this.RaisePropertyChanged("Menus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Application", Namespace="http://schemas.datacontract.org/2004/07/SecurityService")]
    [System.SerializableAttribute()]
    public partial class Application : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string App_DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int App_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string App_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cargo_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cargo_JefeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ID_RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumAsociadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Role_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Usuario_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string App_Descripcion {
            get {
                return this.App_DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.App_DescripcionField, value) != true)) {
                    this.App_DescripcionField = value;
                    this.RaisePropertyChanged("App_Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int App_ID {
            get {
                return this.App_IDField;
            }
            set {
                if ((this.App_IDField.Equals(value) != true)) {
                    this.App_IDField = value;
                    this.RaisePropertyChanged("App_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string App_Name {
            get {
                return this.App_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.App_NameField, value) != true)) {
                    this.App_NameField = value;
                    this.RaisePropertyChanged("App_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cargo_ID {
            get {
                return this.Cargo_IDField;
            }
            set {
                if ((this.Cargo_IDField.Equals(value) != true)) {
                    this.Cargo_IDField = value;
                    this.RaisePropertyChanged("Cargo_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo_Jefe {
            get {
                return this.Cargo_JefeField;
            }
            set {
                if ((object.ReferenceEquals(this.Cargo_JefeField, value) != true)) {
                    this.Cargo_JefeField = value;
                    this.RaisePropertyChanged("Cargo_Jefe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID_Role {
            get {
                return this.ID_RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.ID_RoleField, value) != true)) {
                    this.ID_RoleField = value;
                    this.RaisePropertyChanged("ID_Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Menu {
            get {
                return this.MenuField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuField, value) != true)) {
                    this.MenuField = value;
                    this.RaisePropertyChanged("Menu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumAsociado {
            get {
                return this.NumAsociadoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumAsociadoField, value) != true)) {
                    this.NumAsociadoField = value;
                    this.RaisePropertyChanged("NumAsociado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RolCodigo {
            get {
                return this.RolCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.RolCodigoField, value) != true)) {
                    this.RolCodigoField = value;
                    this.RaisePropertyChanged("RolCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role_Name {
            get {
                return this.Role_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Role_NameField, value) != true)) {
                    this.Role_NameField = value;
                    this.RaisePropertyChanged("Role_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Usuario_ID {
            get {
                return this.Usuario_IDField;
            }
            set {
                if ((this.Usuario_IDField.Equals(value) != true)) {
                    this.Usuario_IDField = value;
                    this.RaisePropertyChanged("Usuario_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationCentroCosto", Namespace="http://schemas.datacontract.org/2004/07/SecurityService")]
    [System.SerializableAttribute()]
    public partial class ApplicationCentroCosto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliasCentroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BaseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CentroCosto_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReembolsoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AliasCentro {
            get {
                return this.AliasCentroField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasCentroField, value) != true)) {
                    this.AliasCentroField = value;
                    this.RaisePropertyChanged("AliasCentro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Base {
            get {
                return this.BaseField;
            }
            set {
                if ((this.BaseField.Equals(value) != true)) {
                    this.BaseField = value;
                    this.RaisePropertyChanged("Base");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CentroCosto_ID {
            get {
                return this.CentroCosto_IDField;
            }
            set {
                if ((this.CentroCosto_IDField.Equals(value) != true)) {
                    this.CentroCosto_IDField = value;
                    this.RaisePropertyChanged("CentroCosto_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Nivel {
            get {
                return this.NivelField;
            }
            set {
                if ((this.NivelField.Equals(value) != true)) {
                    this.NivelField = value;
                    this.RaisePropertyChanged("Nivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Padre {
            get {
                return this.PadreField;
            }
            set {
                if ((object.ReferenceEquals(this.PadreField, value) != true)) {
                    this.PadreField = value;
                    this.RaisePropertyChanged("Padre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Reembolso {
            get {
                return this.ReembolsoField;
            }
            set {
                if ((this.ReembolsoField.Equals(value) != true)) {
                    this.ReembolsoField = value;
                    this.RaisePropertyChanged("Reembolso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationMenu", Namespace="http://schemas.datacontract.org/2004/07/SecurityService")]
    [System.SerializableAttribute()]
    public partial class ApplicationMenu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControladorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Menu_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PosicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VistaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Controlador {
            get {
                return this.ControladorField;
            }
            set {
                if ((object.ReferenceEquals(this.ControladorField, value) != true)) {
                    this.ControladorField = value;
                    this.RaisePropertyChanged("Controlador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Menu_ID {
            get {
                return this.Menu_IDField;
            }
            set {
                if ((this.Menu_IDField.Equals(value) != true)) {
                    this.Menu_IDField = value;
                    this.RaisePropertyChanged("Menu_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Padre {
            get {
                return this.PadreField;
            }
            set {
                if ((this.PadreField.Equals(value) != true)) {
                    this.PadreField = value;
                    this.RaisePropertyChanged("Padre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Posicion {
            get {
                return this.PosicionField;
            }
            set {
                if ((this.PosicionField.Equals(value) != true)) {
                    this.PosicionField = value;
                    this.RaisePropertyChanged("Posicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vista {
            get {
                return this.VistaField;
            }
            set {
                if ((object.ReferenceEquals(this.VistaField, value) != true)) {
                    this.VistaField = value;
                    this.RaisePropertyChanged("Vista");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CentroCostosData", Namespace="http://schemas.datacontract.org/2004/07/SecurityService")]
    [System.SerializableAttribute()]
    public partial class CentroCostosData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebInventario2._0.ServiciosGUC.ApplicationCentroCosto[] CentrosCostosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebInventario2._0.ServiciosGUC.ApplicationCentroCosto[] CentrosCostos {
            get {
                return this.CentrosCostosField;
            }
            set {
                if ((object.ReferenceEquals(this.CentrosCostosField, value) != true)) {
                    this.CentrosCostosField = value;
                    this.RaisePropertyChanged("CentrosCostos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosGUC.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Authenticate", ReplyAction="http://tempuri.org/IService/AuthenticateResponse")]
        WebInventario2._0.ServiciosGUC.UserData Authenticate(string username, string password, string codAplicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Authenticate", ReplyAction="http://tempuri.org/IService/AuthenticateResponse")]
        System.Threading.Tasks.Task<WebInventario2._0.ServiciosGUC.UserData> AuthenticateAsync(string username, string password, string codAplicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AccesoModulo", ReplyAction="http://tempuri.org/IService/AccesoModuloResponse")]
        bool AccesoModulo(int AplicacionID, string Controlador, string Vista, string Roles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AccesoModulo", ReplyAction="http://tempuri.org/IService/AccesoModuloResponse")]
        System.Threading.Tasks.Task<bool> AccesoModuloAsync(int AplicacionID, string Controlador, string Vista, string Roles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMenuCompletoSB", ReplyAction="http://tempuri.org/IService/GetMenuCompletoSBResponse")]
        WebInventario2._0.ServiciosGUC.UserData GetMenuCompletoSB(int aplicacionID, string roles, string ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMenuCompletoSB", ReplyAction="http://tempuri.org/IService/GetMenuCompletoSBResponse")]
        System.Threading.Tasks.Task<WebInventario2._0.ServiciosGUC.UserData> GetMenuCompletoSBAsync(int aplicacionID, string roles, string ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMenuCompletoSUM", ReplyAction="http://tempuri.org/IService/GetMenuCompletoSUMResponse")]
        WebInventario2._0.ServiciosGUC.UserData GetMenuCompletoSUM(int aplicacionID, string roles, string ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMenuCompletoSUM", ReplyAction="http://tempuri.org/IService/GetMenuCompletoSUMResponse")]
        System.Threading.Tasks.Task<WebInventario2._0.ServiciosGUC.UserData> GetMenuCompletoSUMAsync(int aplicacionID, string roles, string ruta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCentroCostoUsuario", ReplyAction="http://tempuri.org/IService/GetCentroCostoUsuarioResponse")]
        WebInventario2._0.ServiciosGUC.CentroCostosData GetCentroCostoUsuario(int UsuarioID, int CajaMenuda, int Base);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCentroCostoUsuario", ReplyAction="http://tempuri.org/IService/GetCentroCostoUsuarioResponse")]
        System.Threading.Tasks.Task<WebInventario2._0.ServiciosGUC.CentroCostosData> GetCentroCostoUsuarioAsync(int UsuarioID, int CajaMenuda, int Base);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCentrosCosto", ReplyAction="http://tempuri.org/IService/GetCentrosCostoResponse")]
        WebInventario2._0.ServiciosGUC.CentroCostosData GetCentrosCosto(int CajaMenuda, int Base, int Todos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetCentrosCosto", ReplyAction="http://tempuri.org/IService/GetCentrosCostoResponse")]
        System.Threading.Tasks.Task<WebInventario2._0.ServiciosGUC.CentroCostosData> GetCentrosCostoAsync(int CajaMenuda, int Base, int Todos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMenus", ReplyAction="http://tempuri.org/IService/GetMenusResponse")]
        WebInventario2._0.ServiciosGUC.ApplicationMenu[] GetMenus(string aplicacionID, string rolesID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMenus", ReplyAction="http://tempuri.org/IService/GetMenusResponse")]
        System.Threading.Tasks.Task<WebInventario2._0.ServiciosGUC.ApplicationMenu[]> GetMenusAsync(string aplicacionID, string rolesID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WebInventario2._0.ServiciosGUC.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WebInventario2._0.ServiciosGUC.IService>, WebInventario2._0.ServiciosGUC.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebInventario2._0.ServiciosGUC.UserData Authenticate(string username, string password, string codAplicacion) {
            return base.Channel.Authenticate(username, password, codAplicacion);
        }
        
        public System.Threading.Tasks.Task<WebInventario2._0.ServiciosGUC.UserData> AuthenticateAsync(string username, string password, string codAplicacion) {
            return base.Channel.AuthenticateAsync(username, password, codAplicacion);
        }
        
        public bool AccesoModulo(int AplicacionID, string Controlador, string Vista, string Roles) {
            return base.Channel.AccesoModulo(AplicacionID, Controlador, Vista, Roles);
        }
        
        public System.Threading.Tasks.Task<bool> AccesoModuloAsync(int AplicacionID, string Controlador, string Vista, string Roles) {
            return base.Channel.AccesoModuloAsync(AplicacionID, Controlador, Vista, Roles);
        }
        
        public WebInventario2._0.ServiciosGUC.UserData GetMenuCompletoSB(int aplicacionID, string roles, string ruta) {
            return base.Channel.GetMenuCompletoSB(aplicacionID, roles, ruta);
        }
        
        public System.Threading.Tasks.Task<WebInventario2._0.ServiciosGUC.UserData> GetMenuCompletoSBAsync(int aplicacionID, string roles, string ruta) {
            return base.Channel.GetMenuCompletoSBAsync(aplicacionID, roles, ruta);
        }
        
        public WebInventario2._0.ServiciosGUC.UserData GetMenuCompletoSUM(int aplicacionID, string roles, string ruta) {
            return base.Channel.GetMenuCompletoSUM(aplicacionID, roles, ruta);
        }
        
        public System.Threading.Tasks.Task<WebInventario2._0.ServiciosGUC.UserData> GetMenuCompletoSUMAsync(int aplicacionID, string roles, string ruta) {
            return base.Channel.GetMenuCompletoSUMAsync(aplicacionID, roles, ruta);
        }
        
        public WebInventario2._0.ServiciosGUC.CentroCostosData GetCentroCostoUsuario(int UsuarioID, int CajaMenuda, int Base) {
            return base.Channel.GetCentroCostoUsuario(UsuarioID, CajaMenuda, Base);
        }
        
        public System.Threading.Tasks.Task<WebInventario2._0.ServiciosGUC.CentroCostosData> GetCentroCostoUsuarioAsync(int UsuarioID, int CajaMenuda, int Base) {
            return base.Channel.GetCentroCostoUsuarioAsync(UsuarioID, CajaMenuda, Base);
        }
        
        public WebInventario2._0.ServiciosGUC.CentroCostosData GetCentrosCosto(int CajaMenuda, int Base, int Todos) {
            return base.Channel.GetCentrosCosto(CajaMenuda, Base, Todos);
        }
        
        public System.Threading.Tasks.Task<WebInventario2._0.ServiciosGUC.CentroCostosData> GetCentrosCostoAsync(int CajaMenuda, int Base, int Todos) {
            return base.Channel.GetCentrosCostoAsync(CajaMenuda, Base, Todos);
        }
        
        public WebInventario2._0.ServiciosGUC.ApplicationMenu[] GetMenus(string aplicacionID, string rolesID) {
            return base.Channel.GetMenus(aplicacionID, rolesID);
        }
        
        public System.Threading.Tasks.Task<WebInventario2._0.ServiciosGUC.ApplicationMenu[]> GetMenusAsync(string aplicacionID, string rolesID) {
            return base.Channel.GetMenusAsync(aplicacionID, rolesID);
        }
    }
}
