//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AF_LOG
    {
        public int ID { get; set; }
        public string ActivoFijo { get; set; }
        public string Base { get; set; }
        public string AreaComercial { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
