//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ajustes_SecuenciaArchivos
    {
        [Key]
        public int num_documento { get; set; }
        public System.DateTime Fecha_Crea { get; set; }
        public string Usuario_Crea { get; set; }
        public System.DateTime Fecha_Mod { get; set; }
        public string Usuario_Mod { get; set; }
    }
}
