//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aplicacion()
        {
            this.Acceso = new HashSet<Acceso>();
            this.AplicacionRol = new HashSet<AplicacionRol>();
            this.Menu = new HashSet<Menu>();
            this.UsuarioAplicacion = new HashSet<UsuarioAplicacion>();
            this.UsuarioRol = new HashSet<UsuarioRol>();
        }
    
        public int Aplicacion_ID { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioCreador { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public int UsuarioModificador { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Activo { get; set; }
        public string Descripcion { get; set; }
        public string Ruta { get; set; }
        public string Codigo { get; set; }
        public string Version { get; set; }
        public string RutaSetup { get; set; }
        public string Desarrollador { get; set; }
        public string Soporte { get; set; }
        public string NombreDB { get; set; }
        public string IPDB { get; set; }
        public string Lenguaje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acceso> Acceso { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AplicacionRol> AplicacionRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu> Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioAplicacion> UsuarioAplicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioRol> UsuarioRol { get; set; }
    }
}
