//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentroCostoUsuario
    {
        public int CentroCostoUsuario_ID { get; set; }
        public int CentroCosto_ID { get; set; }
        public int Usuario_ID { get; set; }
        public Nullable<int> UsuarioCreador { get; set; }
        public Nullable<int> UsuarioModificador { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual CentroCosto CentroCosto { get; set; }
    }
}
