//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciclico_Ubicacion
    {
        public long Id { get; set; }
        public int Ubicacion_ID { get; set; }
        public int Base_ID { get; set; }
        public int Estatus_ID { get; set; }
        public string Codigo { get; set; }
        public bool Auditoria { get; set; }
        public string Dispositivo { get; set; }
        public int UsuarioCreador { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Procesado { get; set; }
        public Nullable<System.DateTime> FechaProcesado { get; set; }
    }
}
