//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConteoDiario_GruposAprobacionAjustes
    {
        public int Id_Grupo { get; set; }
        public string Nombre { get; set; }
        public string Comentarios { get; set; }
        public Nullable<decimal> monto_min { get; set; }
        public Nullable<decimal> monto_max { get; set; }
        public bool activo { get; set; }
        public Nullable<System.DateTime> Fecha_Crea { get; set; }
        public string Usuario_Crea { get; set; }
        public Nullable<System.DateTime> Fecha_Mod { get; set; }
        public string Usuario_Mod { get; set; }
    }
}
