//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ConteoDiario_Detalle
    {
        [Key]
        public int ConteoDiario_Detalle_ID { get; set; }
        public int ConteoDiario_ID { get; set; }
        public decimal sku_id { get; set; }
        public string condicion { get; set; }
        public bool activo { get; set; }
        public Nullable<int> tot_disponible { get; set; }
        public Nullable<decimal> tot_costo { get; set; }
        public Nullable<System.DateTime> Fec_UltEntrada { get; set; }
        public Nullable<System.DateTime> Fec_UltVenta { get; set; }
    }
}
