//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConteoDiario
    {
        public int ConteoDiario_ID { get; set; }
        public int Base { get; set; }
        public string CodDivision { get; set; }
        public System.DateTime fecha_conteo { get; set; }
        public Nullable<int> cant_usuarios { get; set; }
        public Nullable<int> upc_x_usuario { get; set; }
        public System.DateTime Fecha_Crea { get; set; }
        public string Usuario_Crea { get; set; }
        public System.DateTime Fecha_Mod { get; set; }
        public string Usuario_Mod { get; set; }
        public Nullable<int> Id_Condicion { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime Fecha_Status { get; set; }
        public string Usuario_Status { get; set; }
        public int origen { get; set; }
        public Nullable<bool> en_uso { get; set; }
        public Nullable<System.DateTime> fecha_en_uso { get; set; }
        public string Usuario_Actual { get; set; }
        public string grouping_label { get; set; }
    }
}
