//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control_Inventario_Sku_20231226
    {
        public int cis_id { get; set; }
        public string cis_control_inventario { get; set; }
        public short cis_localizacion { get; set; }
        public int cis_base { get; set; }
        public decimal cis_sku_id { get; set; }
        public decimal cis_estilo_id { get; set; }
        public string cis_estilo_cod { get; set; }
        public string cis_estilo_desc { get; set; }
        public string cis_talla { get; set; }
        public string cis_color { get; set; }
        public string cis_marca { get; set; }
        public string cis_hcod_grupo_estilo { get; set; }
        public string cis_hcod_grupo_estilo_desc { get; set; }
        public string cis_hcod_grupo_doc { get; set; }
        public string cis_hcod_grupo_doc_desc { get; set; }
        public Nullable<int> cis_inventario_teorico { get; set; }
        public Nullable<decimal> cis_costo { get; set; }
        public Nullable<System.DateTime> cis_fecha_creacion { get; set; }
    }
}
