//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConteoDiario_Analisis
    {
        public int ConteoDiario_Analisis_ID { get; set; }
        public int ConteoDiario_ID { get; set; }
        public decimal sku_id { get; set; }
        public Nullable<int> inventario_teorico { get; set; }
        public Nullable<int> contado { get; set; }
        public Nullable<int> contado_final { get; set; }
        public Nullable<bool> aplicar_ajuste { get; set; }
        public string motivo_ajuste { get; set; }
        public string comentario { get; set; }
        public System.DateTime Fecha_Crea { get; set; }
        public string Usuario_Crea { get; set; }
        public System.DateTime Fecha_Mod { get; set; }
        public string Usuario_Mod { get; set; }
        public Nullable<bool> procesado { get; set; }
        public Nullable<System.DateTime> Fecha_Proc { get; set; }
        public string Usuario_Proc { get; set; }
        public Nullable<int> diferencia { get; set; }
        public Nullable<int> diferencia_final { get; set; }
        public Nullable<decimal> tot_costo_teorico { get; set; }
        public Nullable<decimal> costo_promedio { get; set; }
        public Nullable<int> contado_final_analisis { get; set; }
        public Nullable<bool> aplicar_ajuste_analisis { get; set; }
        public string motivo_ajuste_analisis { get; set; }
        public string comentario_analisis { get; set; }
        public Nullable<int> contado_final_aprobacion { get; set; }
        public Nullable<bool> aplicar_ajuste_aprobacion { get; set; }
        public string motivo_ajuste_aprobacion { get; set; }
        public string comentario_aprobacion { get; set; }
        public Nullable<int> diferencia_final_analisis { get; set; }
        public Nullable<int> diferencia_final_aprobacion { get; set; }
    }
}
