//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control_Inventario_Documentos
    {
        public int id { get; set; }
        public string control_inventario { get; set; }
        public short localizacion { get; set; }
        public int @base { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_conteo { get; set; }
        public int id_tipo_conteo { get; set; }
        public Nullable<System.DateTime> fecha_limite_proceso { get; set; }
        public string Usuario_Crea { get; set; }
        public Nullable<System.DateTime> Fecha_Mod { get; set; }
        public string Usuario_Mod { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Estado { get; set; }
        public string Usuario_Estado { get; set; }
        public Nullable<bool> sw_lock { get; set; }
        public Nullable<System.DateTime> fecha_lock { get; set; }
        public string Usuario_lock { get; set; }
    }
}
