//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control_Inv_EstilosTmp
    {
        public int id { get; set; }
        public string document_no { get; set; }
        public Nullable<decimal> sku_id { get; set; }
        public Nullable<decimal> style_id { get; set; }
        public string style_code { get; set; }
        public string long_desc { get; set; }
        public string size { get; set; }
        public string color { get; set; }
        public string marca { get; set; }
        public string hie_group_code_style { get; set; }
        public string hie_group_style_label { get; set; }
        public string hierarchy_group_code_Doc { get; set; }
        public string hie_group_Doc_label { get; set; }
        public Nullable<short> location_id { get; set; }
    }
}
