//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConteoCiclico_DivisionesZonas
    {
        public int Id { get; set; }
        public int ConteoCiclico_Id { get; set; }
        public string Zona { get; set; }
        public string Ubicacion { get; set; }
        public string Tipo_Ubicacion { get; set; }
        public int Usuario_Id { get; set; }
        public System.DateTime Fecha_Creada { get; set; }
    }
}
