//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control_Inv_Upc_SinDoc
    {
        public int sd_id { get; set; }
        public string sd_control_inventario { get; set; }
        public Nullable<System.DateTime> sd_fecha_contado { get; set; }
        public Nullable<int> sd_base { get; set; }
        public string sd_estilo { get; set; }
        public Nullable<decimal> sd_sku_id { get; set; }
        public string sd_upc { get; set; }
        public Nullable<int> sd_cantidad_contada { get; set; }
        public string sd_comentario { get; set; }
        public string sd_usuario_proceso { get; set; }
        public Nullable<System.DateTime> sd_fecha_proceso { get; set; }
    }
}
