//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Detalle_Ajustes_Inventario_MERCH
    {
        [Key]
        public int id_ajuste_detalle { get; set; }
        public int id_ajuste { get; set; }
        public decimal sku_id { get; set; }
        public int units { get; set; }
        public decimal costo_promedio { get; set; }
        public decimal monto { get; set; }
    }
}
