//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Detalle_Archivos_AjustesManuales
    {
        [Key]
        public int Detalle_Archivos_AjustesManuales_Id { get; set; }
        public int Archivos_AjustesManuales_Id { get; set; }
        public string UPC { get; set; }
        public Nullable<int> PIEZAS { get; set; }
        public Nullable<int> Base { get; set; }
        public string ESTILO { get; set; }
        public string COLOR { get; set; }
        public string TALLA { get; set; }
    }
}
