//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario_Conteo
    {
        public int Inventario_Conteo_Id { get; set; }
        public int Base { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Fin { get; set; }
        public string tipo_ubicacion { get; set; }
        public string ubicacion { get; set; }
        public int Cantidad { get; set; }
        public string style_code { get; set; }
        public Nullable<decimal> sku_id { get; set; }
        public Nullable<int> id_tipo_conteo { get; set; }
        public Nullable<int> documento_conteo { get; set; }
        public Nullable<bool> ajuste_conteo { get; set; }
        public string comentario { get; set; }
        public short estado { get; set; }
        public Nullable<System.DateTime> Fecha_Crea { get; set; }
        public string Usuario_Crea { get; set; }
        public Nullable<System.DateTime> Fecha_Mod { get; set; }
        public string Usuario_Mod { get; set; }
        public Nullable<System.DateTime> Fecha_Estado { get; set; }
        public string Usuario_Estado { get; set; }
    }
}
