//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario_DetalleConteo
    {
        public int Inventario_DetalleConteo_Id { get; set; }
        public int Inventario_Conteo_Id { get; set; }
        public int Base { get; set; }
        public System.DateTime Fecha { get; set; }
        public string tipo_ubicacion { get; set; }
        public string ubicacion { get; set; }
        public string CodigoBarra { get; set; }
        public int Cantidad { get; set; }
        public string style_code { get; set; }
        public Nullable<decimal> sku_id { get; set; }
        public string IdUsuario { get; set; }
        public string mensaje { get; set; }
    }
}
