//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class JerarquiasMERCH
    {
        [Key]
        public string COD_DIVISION { get; set; }
        public string DESC_DIVISION { get; set; }
        public string COD_DEPARTAMENTO { get; set; }
        public string DESC_DEPARTAMENTO { get; set; }
        public string COD_CLASE { get; set; }
        public string DESC_CLASE { get; set; }
        public string COD_SUBCLASE { get; set; }
        public string DESC_SUBCLASE { get; set; }
        public int ID_JERARQUIA_MERCH { get; set; }
    }
}
