//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LogGeneracion_Tareas_ConteoDiario
    {
        [Key]
        public int LogGeneracion_Tareas_ConteoDiario_ID { get; set; }
        public Nullable<System.DateTime> Fec_Ini { get; set; }
        public Nullable<System.DateTime> Fec_Fin { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Cantidad_Tareas { get; set; }
        public Nullable<System.DateTime> fecha_conteo { get; set; }
    }
}
