//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebInventario2._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tareas_ConteoDiario
    {
        [Key]
        public int Tareas_ConteoDiario_ID { get; set; }
        public int ConteoDiario_ID { get; set; }
        public int Base { get; set; }
        public decimal style_id { get; set; }
        public string style_code { get; set; }
        public Nullable<int> LogGeneracion_Tareas_ConteoDiario_ID { get; set; }
        public System.DateTime Fecha_Crea { get; set; }
        public string Usuario_Crea { get; set; }
        public System.DateTime Fecha_Mod { get; set; }
        public string Usuario_Mod { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime Fecha_Status { get; set; }
        public string Usuario_Status { get; set; }
        public string tipo_ubicacion { get; set; }
        public Nullable<bool> en_uso { get; set; }
        public Nullable<System.DateTime> Fecha_Asignado { get; set; }
        public string Usuario_Asignado { get; set; }
        public int origen { get; set; }
        public int prioridad { get; set; }
        public string ubicacion { get; set; }
        public Nullable<bool> tarea_omitida { get; set; }
        public Nullable<int> Motivo_ID { get; set; }
    }
}
